pages_index:
  path: /
  controller: App\Controller\PageController::index


trick_show:
  path: /tricks/{group_slug}/{trick_slug}
  controller: App\Controller\TrickController::show

trick_list:
  path: /tricks
  controller: App\Controller\TrickController::list

trick_list_group:
  path: /tricks/{slug}
  controller: App\Controller\TrickController::list

security_register:
  path: /register
  controller: App\Controller\SecurityController:register

security_login:
  path: /login
  controller: App\Controller\SecurityController:login


security_logout:
  path: /logout
  controller: App\Controller\SecurityController:logout